Repository eiffel-community/eiffel-intelligence, pull requests merged in 2019-08, with the labels that each got.

#312 Compatibility documentation
  README.md
  wiki/markdown/compatibility.md
Labels: documentation

#309 debugging multiple subscription notification when repeat flag is off
  src/functionaltests/java/com/ericsson/ei/notifications/trigger/SubscriptionNotificationSteps.java
  src/main/java/com/ericsson/ei/subscription/RunSubscription.java
  src/test/java/com/ericsson/ei/flowtests/FlowSourceChangeObject.java
  src/test/java/com/ericsson/ei/flowtests/FlowTest.java
  src/test/java/com/ericsson/ei/flowtests/FlowTest2.java
  src/test/java/com/ericsson/ei/flowtests/FlowTestBase.java
  src/test/java/com/ericsson/ei/flowtests/TrafficGeneratedTest.java
  src/test/java/com/ericsson/ei/test/utils/TestConfigs.java
  src/test/java/com/ericsson/ei/waitlist/TestWaitListWorker.java
Labels: bug

#315 Add support for multiple ldap connections
  pom.xml
  src/functionaltests/java/com/ericsson/ei/subscriptions/authentication/AuthenticationSteps.java
  src/functionaltests/java/com/ericsson/ei/subscriptions/authentication/TestAuthenticationRunner.java
  src/functionaltests/java/com/ericsson/ei/utils/TestLDAPInitializer.java
  src/functionaltests/java/com/ericsson/ei/utils/TestLDAPStarter.java
  src/functionaltests/resources/features/authentication.feature
  src/functionaltests/resources/features/authenticationMultiLDAP.feature
  src/functionaltests/resources/ldap-users-first.ldif
  src/functionaltests/resources/ldap-users-second.ldif
  src/main/java/com/ericsson/ei/EndpointSecurity.java
  src/main/java/com/ericsson/ei/config/ConfigurationLogger.java
  src/main/java/com/ericsson/ei/controller/model/ParseInstanceInfoEI.java
  src/main/resources/application.properties
  wiki/markdown/configuration.md
Labels: enhancement
